### ISSUE TITLE
 System.IO.FileLoadException: Could not load file or assembly 'Google.Apis, Version=1.31.1.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

### ISSUE THREAD

**Issue by Saritha535** [googleads/googleads-dotnet-lib#177]
Hi Team,

I am using Adwords API for developing excel add-in.
Before V201802 everything working fine. after release of Adwords API V201802 my application is not supporting properly. I am using Visual Studio 2015 for older Adwords Versions After releasing of V201802 its not supported I installed VS2017 and updated framework 4.5.2 because latest version of AdWOrds api is supported only 4.5.2.

Could not create an instance of startup object project.ThisAddIn in assembly project, Version=3.5.3.0, Culture=neutral, PublicKeyToken=null.

************** Exception Text **************
Microsoft.VisualStudio.Tools.Applications.Runtime.CannotCreateStartupObjectException: Could not create an instance of startup object project.ThisAddIn in assembly project, Version=3.5.3.0, Culture=neutral, PublicKeyToken=null. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Google.Apis, Version=1.31.1.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at project.ThisAddIn..ctor(ApplicationFactory factory, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.ExecuteCustomization.CreateEntryPoint(String entryPointTypeName)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.ExecuteCustomization.CreateEntryPoint(String entryPointTypeName)
   at Microsoft.VisualStudio.Tools.Office.Runtime.DomainCreator.ExecuteCustomization.Microsoft.VisualStudio.Tools.Office.Runtime.Interop.IExecuteCustomization2.LoadEntryPoints(IntPtr serviceProvider)

**Comment by AnashOommen** [comment]
Hi,

Was this issue resolved?
