### ISSUE TITLE
unhandled exception Google DFP dotnet v23.0.0

### ISSUE THREAD

**Issue by FredBis** [googleads/googleads-dotnet-lib#195]
Hi,

we are currently using the Google DFP dotnet v22.4.0 v201711 APIs which no longer work from December 1st

we are trying to migrate to version v23.0.0 v201802 but at runtime we have the following error message

Application: PREF_CalbizDfp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
Stack:
at Google.Api.Ads.Dfp.Lib.DfpServiceFactory.CheckServicePreconditions(Google.Api.Ads.Common.Lib.ServiceSignature)
at Google.Api.Ads.Dfp.Lib.DfpServiceFactory.CreateService(Google.Api.Ads.Common.Lib.ServiceSignature, Google.Api.Ads.Common.Lib.AdsUser, System.Uri)
at Google.Api.Ads.Common.Lib.AdsUser.GetService(Google.Api.Ads.Common.Lib.ServiceSignature, System.Uri)
at Google.Api.Ads.Common.Lib.AdsUser.GetService(Google.Api.Ads.Common.Lib.ServiceSignature, System.String)
at CDM.PREF_CalbizDfp.FonctionsClient.MajClientDFP(CDM.PREF_CalbizDfp.Campagne)
at CDM.PREF_CalbizDfp.FonctionsCampagne.CreaMajCampagne(CDM.PREF_CalbizDfp.Campagne)
at CDM.PREF_CalbizDfp.Scheduler.SchedulerThreadProc()
at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.ThreadHelper.ThreadStart()

it seems that a Google API calls a dll that is not in the right version
 
Could you help us to identify the problem ?
 
Thanks in advance, 
Best Regards

**Comment by AnashOommen** [comment]
Looks like your framework version is v4.0.30319? The DFP .NET client library requires at least .NET 452.
