### ISSUE TITLE
Timeout during report execution causes null reference exception

### ISSUE THREAD

**Issue by AdrianPell** [googleads/googleads-dotnet-lib#73]
I have a case where my custom report request times out (setting Timeout<>-1 in app.config).  When this happens, I get a null reference exception in the logging code.

Stack trace:
```
Object reference not set to an instance of an object.
   at Google.Api.Ads.Common.Logging.LogEntry.LogResponseDetails(WebResponse response, String responseBody, ISet`1 fieldsToMask, TraceFormatter formatter)
   at Google.Api.Ads.Common.Logging.LogEntry.LogResponse(WebResponse response, Boolean isFailure, String formattedMessage)
   at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.DownloadReport(String downloadUrl, String postBody)
   at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.GetReport()
   at Google.Api.Ads.Common.Util.Reports.AdsReportUtilities.GetResponse()
   at Google.Api.Ads.AdWords.Util.Reports.ReportUtilities.GetResponse()
```

Presumably, the WebException that gets thrown doesn't contain a WebResponse since there never was a response.

**Comment by AnashOommen** [comment]
I have a fix in place, this should go live in the next push.

**Comment by AdrianPell** [comment]
Hi Anash

Did this get pushed out in one of the recent releases?  I didn't see it in the release notes - and if so, how would I detect a timeout now?  They're kind of hard to generate ... :-)

Thanks

Adrian

**Comment by AnashOommen** [comment]
If you set a Timeout in your App.config, it will be used by all
connections. Try setting it to 100ms or so and debug, it should get
triggered pretty easily.

Anash
